### ISSUE TITLE
keyword arguments on Feats class should be descriptive

### ISSUE THREAD

**Issue by korymath** [kylemath/DeepEEG#11]
Currently line, https://github.com/kylemath/DeepEEG/blob/5df314a826baa08c7a46eb832a400b7b47fb41db/utils.py#L41 reads

```sh
def __init__(self, a=2, b=[1,1], c=[16,], d=1, e='1', f=1, g=1, h=1, i=1, j=1, k=1):
```

These attributes are then set with keyword arguments, they should use the keyword names, rather than the alphabetical placeholders.

**Comment by kylemath** [comment]
fixed with commit - https://github.com/kylemath/DeepEEG/commit/3670c81a2526d38a7553382ae951ca6ccfa98766#diff-04d2c9518498da64bfa9db44c6211645
