### ISSUE TITLE
Complex inputs?

### ISSUE THREAD

**Issue by kylemath** [kylemath/DeepEEG#15]

**Comment by kylemath** [comment]
starting to work on this in https://github.com/kylemath/DeepEEG/pull/17, 
as a first try, just concatenate the values

**Comment by kylemath** [comment]
https://arxiv.org/pdf/1705.09792.pdf

**Comment by kylemath** [comment]
https://github.com/ChihebTrabelsi/deep_complex_networks

**Comment by korymath** [comment]
Closed with: 

https://github.com/kylemath/DeepEEG/commit/498148f206bc96476d57f77da777b2f91ab8b080
