### ISSUE TITLE
Move pip requirements to requirements.txt

### ISSUE THREAD

**Issue by korymath** [kylemath/DeepEEG#2]
pip installations should be listed in a requirements.txt file

Make a new text file called requirements.txt with the following text:

```
h5py==2.9.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
mne==0.17.0
numpy==1.16.1
PyYAML==3.13
scipy==1.2.0
six==1.12.0
```

And then the installation of the packages can be done with a one-line call:

```
pip install -r requirements.txt
```

**Comment by kylemath** [comment]
moved over
