### ISSUE TITLE
Data for running DeepEEG_Sim is missing

### ISSUE THREAD

**Issue by shirans** [kylemath/DeepEEG#35]
Hi

This repository looks great! I'd like to run your example code, but it seems the data on 'visual/cueing' is missing. I tried to follow the README, and also run the Colab noteblook DeepEEG_Sim, but the code fails find the files. I also tried to look it up both on this repo and the eeg-notebook repo. Do you think you could upload a few example datasets to run the code with?

**Comment by kylemath** [comment]
The issue is an update to eeg-notebooks,
The old eeg-notebooks is now called: https://github.com/kylemath/eeg-notebooks_v0.1

I have tried addressing this in https://github.com/kylemath/DeepEEG/pull/36, but I am running into other dependency issues

**Comment by shirans** [comment]
Not sure what's the issues, works for me with v0.1. Thanks!
