### ISSUE TITLE
Unittest working? 

### ISSUE THREAD

**Issue by kylemath** [kylemath/DeepEEG#6]
@korymath - 

```python
python -m unittest 
```
says 0 tests complete

but
```python
python tests.py
```
runs on its own and says 3 tests complete,
is the unittest working correctly?

**Comment by kylemath** [comment]
fixed with
```python
python -m unittest test
```

https://github.com/kylemath/DeepEEG/commit/25321e40c7e1c3ea192cda194edc2b4708df3f69#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by korymath** [comment]
Thank you!
